config/routes.rb
Rails.application.routes.draw do
  resources :teams
  
  get 'manager/index'=>'manager#index'
  root 'contests#index'
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :contests

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
    mount_uploader :image, ImageUploader
    acts_as_taggable
    
    has_many :teams
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]
  # GET /contests
  # GET /contests.json
  def index
    @search = Contest.search(params[:q])
    if params[:tag]
      @contests = Contest.tagged_with(params[:tag])
    elsif
      @contests = @search.result(distinct: true)
    else
      @contests = Contest.all
    end
 # @people = @q.result(distinct: true)
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    @team_list = Team.where(contest_id: params[:id]).order(id: :desc)
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:title, :period, :introduce, :category, :tag_list, :image)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
    def tag_icons(tag_list)
        tag_list.map do | tag |
            "<a href='/contests?tag=#{CGI::escape(tag)}' class='tag'>#{tag}</a>"
        end.join(' ').html_safe
    end
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :period %><br>
    <%= f.date_select :period %>
  </div>
  <div class="field">
    <%= f.label :introduce %><br>
    <%= f.text_area :introduce %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, [['리포트', 0],['문학', 1],['아이디어', 2],['만화, 캐릭터', 3],['작명, 슬로건', 4],['게임, 소프트웨어', 5],['광고, 마케팅', 6],['UCC', 7]] %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list, placeholder: '하나 이상의 태그는 콤마(,)로 구분하여 입력하세요.' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing Contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<div class="search_box">
  <div class="position">
 <%= search_form_for @search do |f| %>
   <!--검색기능...-->
   <%= f.search_field :title_or_introduce_cont, class: "searchbeauty", placeholder: '제목 or 내용' %>
   <% end %>
 </div>
 
 
  
<div id="filters" class="button-group">  
  <button type="button" class="btn btn-link btn-sm is-checked hvr-sweep-to-top" data-filter="*">전체보기</button>
  <button type="button" class="btn btn-link btn-sm hvr-sweep-to-top" data-filter=".0">리포트</button>
  <button type="button" class="btn btn-link btn-sm hvr-sweep-to-top" data-filter=".1">문학</button>
  <button type="button" class="btn btn-link btn-sm hvr-sweep-to-top" data-filter=".2">아이디어</button>
  <button type="button" class="btn btn-link btn-sm hvr-sweep-to-top" data-filter=".3">만화, 캐릭터</button>
  <button type="button" class="btn btn-link btn-sm hvr-sweep-to-top" data-filter=".4">작명, 슬로건</button>
  <button type="button" class="btn btn-link btn-sm hvr-sweep-to-top" data-filter=".5">게임, 소프트웨어</button>
  <button type="button" class="btn btn-link btn-sm hvr-sweep-to-top" data-filter=".6">광고, 마케팅</button>
  <button type="button" class="btn btn-link btn-sm hvr-sweep-to-top" data-filter=".7">UCC</button>
</div>

 
</div>



<div class="container mainpage">
  
 
<div class="grid">
  <% @contests.each do |contest| %>
    <div class="element-item transition metal hvr-grow <%= contest.category.to_s %>" data-category="transition" onclick='location.href="<%= contest_path(contest) %>"'>
      <p class="poster_container"><%= image_tag contest.image.url, class: "poster_img"%></p>
      <div class="word_table">
        <p class="name"><%= contest.title %></p>
        <p class ="number"><%= contest.period.to_s %></p>
        <p class="taglist"><%= tag_icons contest.tag_list %></p>
        
      </div>
     </div>
  <% end %>
</div>
  <a class="coloing btn btn-link btn-sm hvr-sweep-to-top" role="button" style="width: 100px; text-align: center;  
     border-width: 2px;  padding: 3px 0px!important; margin-left: 15px;" <a="" href="/contests">전체 목록</a>

</div>

app/views/contests/new.html.erb
<h1>New Contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<div class="tooltip">Hover over me
  <span class="tooltiptext">Tooltip text</span>
</div>


<div class="show container">
  <div class="col-12" style="text-align:center; font-size:3rem; margin:20px auto">
     <strong><%= @contest.title %></strong>
          
  </div>
  <div class="row">
    <div class="col-md-3" >
       <p>
          <%= image_tag(@contest.image.url, width: "100%")%>
        </p>
    </div>
    <div class="col-md-4">
      <div class="card">
        <p id="notice"><%= notice %></p>
        
        <p>
          <strong>마감일 </strong>
          <%= @contest.period %>
        </p>
        
        <p>
          <strong>소개 </strong>
          <%= @contest.introduce %>
        </p>
        
        <p>
          <strong>분야 </strong>
          <%= @contest.category %>
        </p>
        <p>
          <strong>태그 </strong>
          <%= tag_icons @contest.tag_list %>  
        </p>
       
      </div>
    </div>
    
    <div class="col-md-5">
      <div class="card">
          
          <% @team_list.each do |team| %>
            <div class="list_no" style="cursor:pointer"><B><%=team.title%></B> </div>
            <div class="list_member">
                <p><%= User.find(team.user_id).email %></p>
                <a href=''></a>
            </div>
            <br>
          <% end %>
          <!--<div class="list_no" style="cursor:pointer"><B>TEAM 1</B> </div>-->
          <!--<div class="list_member">-->
          <!--    <div>-->
          <!--   <ul>장서정</ul>-->
          <!--   <ul>장순호</ul>-->
          <!--   <ul>장서정</ul>-->
          <!--   <ul>장순호</ul>-->
          <!--    </div>-->
          <!--    <a href=''></a>-->
          <!--</div>-->
          <!--<br>-->
          
          <!--<div class="list_no" style="cursor:pointer"><B>TEAM 2</B></div>-->
          <!--<div class="list_member">-->
          <!--    <div>-->
          <!--    <ul>최성흠</ul>-->
          <!--    <ul>성큼</ul>-->
          <!--    </div>-->
          <!--</div>-->
          <!--<br>-->
          
          <!--<div class="list_no" style="cursor:pointer"><B>TEAM 3</B></div>-->
          <!--<div class="list_member">-->
          <!--    <div>-->
          <!--    <ul>전지원</ul>-->
          <!--    <ul>이동건</ul>-->
          <!--    <ul>양효영</ul>-->
          <!--    </div>-->
          <!--</div>-->
          <!--<br>-->
          
      </div>
    </div>
    </div>
  </div>
  <a href='<%=new_team_path%>?cid=<%=params[:id]%>'>팀 생성</a>
  
  <hr />
  <%= link_to 'Edit', edit_contest_path(@contest) %> |
  <%= link_to 'Back', contests_path %>
</div>



<script type="text/javascript">
  initShowHideDivs();
</script>